In [1]:
## numpy library

In [2]:
# numpy is not a original package in the python it is the package introduced in the python
#numpy = numeric python

In [3]:
import numpy as np

In [4]:
# one dimentional array

In [5]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [6]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [7]:
np.array([1,2,3,"priya",4+5j])

array(['1', '2', '3', 'priya', '(4+5j)'], dtype='<U64')

In [8]:
# upcasting - in the given example some data have integer datatype and some have float
# so numpy convert the integer datatype value into the float datatype

In [9]:
np.array([1,2,3.2,2.5])

array([1. , 2. , 3.2, 2.5])

In [10]:
# upcasting - integer datatype is converted into the string datatype

In [11]:
np.array(["priya","shivaji",1,2,3,4])

array(['priya', 'shivaji', '1', '2', '3', '4'], dtype='<U11')

In [12]:
# two dimentional array

In [13]:
np.array([[1,3],
          [5,6],
         [7,8]])

array([[1, 3],
       [5, 6],
       [7, 8]])

In [14]:
 # three dimentiona array

In [15]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# four dimentional array
# ndmin are used for the to decide the dimention of the array

In [17]:
np.array([1,2,3,4], ndmin = 4)

array([[[[1, 2, 3, 4]]]])

In [18]:
np.array([1,2,3,4], ndmin = 2)

array([[1, 2, 3, 4]])

In [19]:
# chnage the datatype of the array element by using the dtype function

In [20]:
# here change the datatype integer to the complex number

In [21]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
# change the datatype integer to the float

In [23]:
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [24]:
# we can also keep our data  in tuple format
# it will give the similar type of output like list

In [25]:
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [26]:
arr = np.array([[1,2], [3,4]])

In [27]:
arr

array([[1, 2],
       [3, 4]])

In [28]:
type(arr[0][0])

numpy.int32

In [29]:
type(arr[0][1])

numpy.int32

In [30]:
arr[0][0]

1

In [31]:
arr[0][1]

2

In [32]:
# access the element of the array

In [33]:
arr1 = np.array([[1,2],[3,4],[5,6]])

In [34]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
# access the row of the array

In [36]:
arr1[0]

array([1, 2])

In [37]:
arr1[0][1]

2

In [38]:
type(arr1[0][1])

numpy.int32

In [39]:
 # convert the array into the matrix
# mat(), matrix() both functions are used to convert the array into matrix

In [40]:
np.mat(arr1)

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [41]:
m =np.matrix(arr1)

In [42]:
m

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [43]:
# convert the list into the array

In [44]:
l = [1,2,3,4,5,6]

In [45]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [46]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [47]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [48]:
#  asanyarray() function can not convert the subclass of array into any other type
# so matrix is the subtype of the array , asanyarray() function does not change the matrix into array
# where as list is not subtype of the array so it will convert into array

In [49]:
np.asanyarray(m)

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [50]:
# array() function can convert everything into array

In [51]:
np.array(m)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
# asarray() function can be convert everything into array

In [53]:
np.asarray(m)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
# to check the matrix is the subtype of array or not
# issubclass is the inbuilt function

In [55]:
issubclass(np.matrix , np.ndarray)

True

In [56]:
# to check the array is the subclass of the matrix or not 
# array is the parent class of the matrix 

In [57]:
issubclass( np.ndarray, np.matrix )

False

### shallow copy and deep copy

In [58]:
# array element is mutable

In [59]:
arr

array([[1, 2],
       [3, 4]])

In [60]:
a = arr

In [61]:
a

array([[1, 2],
       [3, 4]])

In [62]:
b = np.copy(arr)

In [63]:
b

array([[1, 2],
       [3, 4]])

In [64]:
arr[0][0]

1

In [65]:
arr[0][0]= 54

In [66]:
# when we asign the array in the different variable if we change the value of the original array 
#then it will also change the value of the new array
# a refering the same location like arr

In [67]:
#A shallow copy creates a new compound object and then references the objects contained in the original within it
# It means that any changes made to a copy of an object do reflect in the original object. 

In [68]:
a

array([[54,  2],
       [ 3,  4]])

In [69]:
# if we copy the array and put the copied array into a one variable 
# then chnage the value of the original array then it does not change the value of the copied array
# b refering the another location(create the new location) so changes does not occure in the b

In [70]:
# A deep copy creates a new compound object before inserting copies of the items found in the original into it in a recursive manner.
#It means that any changes made to a copy of the object do not reflect in the original object. 

In [71]:
b

array([[1, 2],
       [3, 4]])

In [72]:
# access the element from the array

In [73]:
# in the arr array only 2 element are present

In [74]:
arr[0:2]

array([[54,  2],
       [ 3,  4]])

In [75]:
arr[0:10]

array([[54,  2],
       [ 3,  4]])

In [76]:
arr[-1]

array([3, 4])

In [77]:
for i in arr:
    print(i)

[54  2]
[3 4]


In [78]:
for i in b:
    print(i)

[1 2]
[3 4]


### difference between list and numpy array

In [79]:
# array - numpy array is the is belongs to the numpy package, all the mathematical formulae inside the numpy is applicable for the numpy array directly.
# list -  is the part of the core python

In [80]:
# fromfunction ()
# in NumPy, the numpy.fromfunction function is used to create an array by applying a specified function 
#to each coordinate in the resulting array. This can be useful for creating arrays based on mathematical operations 
#or custom-defined functions. 
# in this code i= j when it is true then it will display true at the cordinates otherwise it will print the false 

In [81]:
np.fromfunction(lambda i, j: i ==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [82]:
type(np.fromfunction(lambda i,j: i==j, (4,4)))

numpy.ndarray

In [83]:
# here fromfunction are used for the multiply the cordinates of x and y axis

In [84]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [85]:
 # in numpy 0/0 and 1/0 does not give any error
# 0/0 shows the nan and 1/0 shows inf

In [86]:
np.fromfunction(lambda i,j: i/j, (3,3))

C:\Users\Priyanka\AppData\Local\Temp\ipykernel_7916\2105401307.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j: i/j, (3,3))
C:\Users\Priyanka\AppData\Local\Temp\ipykernel_7916\2105401307.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j: i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [87]:
# generator function - are used to generate the data

In [88]:
gen = (i*i for i in range(5))

In [89]:
gen

<generator object <genexpr> at 0x000001D1FF720D60>

In [90]:
def test(x):
    yield x

In [91]:
test(5)

<generator object test at 0x000001D1FF720F20>

In [92]:
np.fromiter(gen, dtype= int)

array([ 0,  1,  4,  9, 16])

In [93]:
# range is also generator function 

In [94]:
np.fromiter(range(5), dtype= float)

array([0., 1., 2., 3., 4.])

In [95]:
# fromstring() function 


In [96]:
np.fromstring('1,2,3,4,5', sep = ",", dtype = int)

array([1, 2, 3, 4, 5])

In [97]:
np.fromstring("123 456 789", sep = " ", dtype = int)

array([123, 456, 789])

In [98]:
np.fromstring("123 456 789", sep = " ", dtype = complex)

array([123.+0.j, 456.+0.j, 789.+0.j])

In [99]:
np.fromstring('1 2 3 4 5', sep = " ", dtype = int)

array([1, 2, 3, 4, 5])

In [100]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [101]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
type(arr1)

numpy.ndarray

In [103]:
# ndim function are used to determine the dimension of the given array

In [104]:
arr1.ndim

2

In [105]:
# size function are used to determine the total no.of element in the given array

In [106]:
arr1.size

9

In [107]:
# shape function are used for determine the no.of rows and no.of columns in the array (i.e nXn)

In [108]:
arr1.shape

(3, 3)

In [109]:
arr1.dtype

dtype('int32')

In [110]:
arr

array([[54,  2],
       [ 3,  4]])

In [111]:
arr.size

4

In [112]:
arr.shape

(2, 2)

In [113]:
arr.ndim

2

In [114]:
arr.dtype

dtype('int32')

In [115]:
# 3 dimentional array

In [116]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]], [[4,3,2,1],[8,7,6,5]]])

In [117]:
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[4, 3, 2, 1],
        [8, 7, 6, 5]]])

In [118]:
arr2.size

16

In [119]:
arr2.ndim

3

In [120]:
# in shape of the array (2,2,4) first 2 represented no.of array, second 2 represnts no.of row, and 4 represented no.of column in the array 
# we have 2 array of the 2X4 size

In [121]:
arr2.shape

(2, 2, 4)

In [122]:
# 4 dimensional array

In [123]:
arr3 = np.array([[[[1,2,3,4],[5,6,7,8]], [[4,3,2,1],[8,7,6,5]],[[9,6,3,2],[8,5,2,1]],[[8,4,1,0],[9,5,1,0]]]])

In [124]:
arr3

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[4, 3, 2, 1],
         [8, 7, 6, 5]],

        [[9, 6, 3, 2],
         [8, 5, 2, 1]],

        [[8, 4, 1, 0],
         [9, 5, 1, 0]]]])

In [125]:
arr3.ndim

4

In [126]:
# the shape of array (1,4,2,4) represented their are four 2X4 array which are represented in one

In [127]:
arr3.shape

(1, 4, 2, 4)

In [128]:
arr3.size

32

In [129]:
# range() function

In [130]:
range(5)

range(0, 5)

In [131]:
list(range(5))

[0, 1, 2, 3, 4]

In [132]:
# we can not creat the the list of the any float number i.e list(range(6.6))
# but in numpy their is the function arange() which can produce a list of the float number
# arange function similar to the range function except the float number


In [133]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [134]:
# in list we can start, end and step the element integer only
# but in the numpy arange function are used for the handling the data in float nature

In [135]:
np.arange(1.5, 5.5,0.5)

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [136]:
np.arange(9,5,-0.5)

array([9. , 8.5, 8. , 7.5, 7. , 6.5, 6. , 5.5])

In [137]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [138]:
# linspace() function
# linspace is an in-built function in Python's NumPy library.
# It is used to create an evenly spaced sequence in a specified interval.

In [139]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [140]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [141]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [142]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [143]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [144]:
# zeros() fuction in the numpy
# this function are used for generate the array which contain only zeros

In [145]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [146]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [147]:
np.zeros([2,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [148]:
# ones() function
# this function are used for creating the array with value 1

In [149]:
np.ones(4)

array([1., 1., 1., 1.])

In [150]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [151]:
np.ones([3, 3,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [152]:
# addition of the 5 in each element of the array

In [153]:
np.ones([3, 3,2]) +5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [154]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [155]:
np.empty([3,4])

array([[9.88778011e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 1.35104624e+161, 4.75177087e-037,
        1.23189154e+165],
       [5.69976191e-038, 9.39623604e+165, 1.70459790e+160,
        2.05908074e+184]])

In [156]:
# eye() function in Python is used to return a two-dimensional array 
# with ones (1) on the diagonal and zeros (0) elsewhere.

In [157]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [159]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [160]:
np.linspace(2,4,4, endpoint =False)

array([2. , 2.5, 3. , 3.5])

In [161]:
np.linspace(2,4,4, endpoint = False, axis = 0)

array([2. , 2.5, 3. , 3.5])

In [162]:
np.linspace([2,4],4, endpoint = False, axis = 0)

array([[2.  , 4.  ],
       [2.04, 4.  ],
       [2.08, 4.  ],
       [2.12, 4.  ],
       [2.16, 4.  ],
       [2.2 , 4.  ],
       [2.24, 4.  ],
       [2.28, 4.  ],
       [2.32, 4.  ],
       [2.36, 4.  ],
       [2.4 , 4.  ],
       [2.44, 4.  ],
       [2.48, 4.  ],
       [2.52, 4.  ],
       [2.56, 4.  ],
       [2.6 , 4.  ],
       [2.64, 4.  ],
       [2.68, 4.  ],
       [2.72, 4.  ],
       [2.76, 4.  ],
       [2.8 , 4.  ],
       [2.84, 4.  ],
       [2.88, 4.  ],
       [2.92, 4.  ],
       [2.96, 4.  ],
       [3.  , 4.  ],
       [3.04, 4.  ],
       [3.08, 4.  ],
       [3.12, 4.  ],
       [3.16, 4.  ],
       [3.2 , 4.  ],
       [3.24, 4.  ],
       [3.28, 4.  ],
       [3.32, 4.  ],
       [3.36, 4.  ],
       [3.4 , 4.  ],
       [3.44, 4.  ],
       [3.48, 4.  ],
       [3.52, 4.  ],
       [3.56, 4.  ],
       [3.6 , 4.  ],
       [3.64, 4.  ],
       [3.68, 4.  ],
       [3.72, 4.  ],
       [3.76, 4.  ],
       [3.8 , 4.  ],
       [3.84, 4.  ],
       [3.88,

In [163]:
np.linspace([2,4],4, endpoint = False, axis = 1)

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [164]:
# logspace. Return numbers spaced evenly on a log scale. 
#In linear space, the sequence starts at base ** start (base to the power of start) and ends with base ** stop (see endpoint below).

In [165]:
np.logspace(2,4,4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [166]:
np.logspace([2,4], 4)

array([[  100.        , 10000.        ],
       [  109.8541142 , 10000.        ],
       [  120.67926406, 10000.        ],
       [  132.57113656, 10000.        ],
       [  145.63484775, 10000.        ],
       [  159.98587196, 10000.        ],
       [  175.75106249, 10000.        ],
       [  193.06977289, 10000.        ],
       [  212.09508879, 10000.        ],
       [  232.99518105, 10000.        ],
       [  255.95479227, 10000.        ],
       [  281.1768698 , 10000.        ],
       [  308.88435965, 10000.        ],
       [  339.32217719, 10000.        ],
       [  372.75937203, 10000.        ],
       [  409.49150624, 10000.        ],
       [  449.8432669 , 10000.        ],
       [  494.17133613, 10000.        ],
       [  542.86754393, 10000.        ],
       [  596.36233166, 10000.        ],
       [  655.12855686, 10000.        ],
       [  719.685673  , 10000.        ],
       [  790.60432109, 10000.        ],
       [  868.51137375, 10000.        ],
       [  954.09

In [167]:
np.logspace([2,4], 4, axis = 1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [10000.        , 10000.        , 10000.        , 10000.        ,
        10000.        ,

In [168]:
d= np.linspace(4,7,40)

In [169]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [170]:
d.ndim

1

In [171]:
d.shape

(40,)

In [172]:
d.size

40

In [173]:
# reshape() fuction are used to change the dimention of the array

In [174]:
a =d.reshape(40,1)

In [175]:
a

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [176]:
# our 1d dat is converted into the 2d

In [177]:
a.ndim

2

In [178]:
# convert the 2d data into 3d array
# make two array of the 2 row , 10 column

In [179]:
a.reshape(2,2,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [180]:
# returns an array of random samples from the uniform distribution over [0,1] .

In [181]:
 np.random.rand(3)

array([0.53244629, 0.02097774, 0.6134036 ])

In [182]:
# random. randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.
# standard normal distribution mean = 0 and standard deviation = 1

In [183]:
np.random.randn(3)

array([-1.07966698,  0.38163522,  0.53365485])

In [184]:
np.random.randn(2,3)

array([[-0.85204837, -0.94267535, -0.64305468],
       [ 0.97097668, -0.63110392, -0.39308919]])

In [185]:
np.random.randn(2,2,3)

array([[[ 0.61679192, -2.16278788,  0.1687031 ],
        [-0.58126938, -0.94245878, -0.16316741]],

       [[-0.09213556, -0.29620058,  0.68190241],
        [-0.30026299, -0.24343144, -1.30480588]]])

In [186]:
# The randint() method returns an integer number selected element from the specified range.

In [187]:
np.random.randint(5)

0

In [188]:
np.random.randint(5)

4

In [189]:
np.random.randint(2,10)

4

In [190]:
np.random.randint(2,10)

9

In [191]:
# generate the 3X3 matrix, all the element of matrix are between the 5 and 10

In [192]:
np.random.randint(5,10, (3,3))

array([[5, 7, 5],
       [8, 6, 7],
       [6, 9, 5]])

In [193]:
arr = np.random.randint(3,9,(3,3))

In [194]:
arr

array([[8, 6, 7],
       [3, 8, 7],
       [6, 7, 6]])

In [195]:
# reshape function are used for the generate the array row and column according to the user
# arrange the data in one row and nine column

In [196]:
arr.reshape(1,9)

array([[8, 6, 7, 3, 8, 7, 6, 7, 6]])

In [197]:
# arrange the data in the 9 row and 1 column

In [198]:
arr.reshape(9,1)

array([[8],
       [6],
       [7],
       [3],
       [8],
       [7],
       [6],
       [7],
       [6]])

In [199]:
arr.reshape(1,1,9)

array([[[8, 6, 7, 3, 8, 7, 6, 7, 6]]])

In [200]:
arr.reshape(3,3,1)

array([[[8],
        [6],
        [7]],

       [[3],
        [8],
        [7]],

       [[6],
        [7],
        [6]]])

In [201]:
# if we give the negative value to the axis then then numpy arrange the data according to the other axis value

In [202]:
# in the below case we put 3 and -1 then the 3 is the no.of row 
# we have the 9 element in the arr so no.of column set based on the given row number

In [203]:
arr.reshape(3, -1)

array([[8, 6, 7],
       [3, 8, 7],
       [6, 7, 6]])

In [204]:
# no. fo row is 1 so the no.of column will be 9

In [205]:
arr.reshape(1,-1)

array([[8, 6, 7, 3, 8, 7, 6, 7, 6]])

In [206]:
# max() function give the maximum number in the array

In [207]:
arr.max()

8

In [208]:
# min() function give the minimum number in  the array

In [209]:
arr.min()

3

In [210]:
# slicing operation on the array

In [211]:
arr1 = np.random.randint(4,10,(5,5))

In [212]:
arr1

array([[7, 9, 7, 5, 4],
       [4, 6, 6, 6, 8],
       [7, 9, 6, 4, 8],
       [9, 4, 9, 9, 6],
       [9, 7, 6, 4, 9]])

In [213]:
arr1.shape

(5, 5)

In [214]:
# extract the data from the right bottom corner of the array with shape 2X2

In [215]:
arr1[3:,3:]

array([[9, 6],
       [4, 9]])

In [216]:
arr1[3:,3:,].shape

(2, 2)

In [217]:
# extract the data from allrow of the 2 column and 4 column

In [218]:
arr1[0:, [1,3]]

array([[9, 5],
       [6, 6],
       [9, 4],
       [4, 9],
       [7, 4]])

In [219]:
arr1

array([[7, 9, 7, 5, 4],
       [4, 6, 6, 6, 8],
       [7, 9, 6, 4, 8],
       [9, 4, 9, 9, 6],
       [9, 7, 6, 4, 9]])

In [220]:
# arr1> 7 this command will print the true false value in the matrix
# when element of the array greater than 7then it will print true otherwise print false

In [221]:
arr1>7


array([[False,  True, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [ True, False, False, False,  True]])

In [222]:
# filter out the data which are greater than the 7

In [223]:
arr1[arr1>7]

array([9, 8, 9, 8, 9, 9, 9, 9, 9])

In [224]:
arr1

array([[7, 9, 7, 5, 4],
       [4, 6, 6, 6, 8],
       [7, 9, 6, 4, 8],
       [9, 4, 9, 9, 6],
       [9, 7, 6, 4, 9]])

In [225]:
arr1*arr1

array([[49, 81, 49, 25, 16],
       [16, 36, 36, 36, 64],
       [49, 81, 36, 16, 64],
       [81, 16, 81, 81, 36],
       [81, 49, 36, 16, 81]])

In [226]:
arr2 = np.random.randint(10,20,(3,3))

In [227]:
arr2

array([[17, 10, 12],
       [16, 17, 19],
       [14, 14, 16]])

In [228]:
arr3 = np.random.randint(1,10,(3,3))

In [229]:
arr3

array([[6, 9, 3],
       [1, 6, 9],
       [7, 6, 4]])

In [230]:
# multiplication of the two array
# for the multiplication of the array both array should have same dimention and shape 

In [231]:
# multiplication of the matrix according to index

In [232]:
arr2 *arr3

array([[102,  90,  36],
       [ 16, 102, 171],
       [ 98,  84,  64]])

In [233]:
# mathematical matrix multiplication
# In which no.of row should be equal to the no.of column


In [234]:
arr2@arr3

array([[196, 285, 189],
       [246, 360, 277],
       [210, 306, 232]])

In [235]:
# array division

In [236]:
arr2/0

C:\Users\Priyanka\AppData\Local\Temp\ipykernel_7916\4133987296.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [237]:
# squaring of the array element

In [238]:
arr2**2

array([[289, 100, 144],
       [256, 289, 361],
       [196, 196, 256]])

In [239]:
# broadcasting

In [240]:
arr4 = np.zeros((3,4))

In [241]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [242]:
a = np.array([1,2,3,4])

In [243]:
a

array([1, 2, 3, 4])

In [244]:
# row wise broadcasting

In [245]:
arr4 +a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [246]:
arr4 +2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [247]:
# columnwise broadcasting

In [248]:
b = np.array([4,5,6])

In [249]:
b

array([4, 5, 6])

In [250]:
b +5

array([ 9, 10, 11])

In [251]:
b.reshape(3,1) + 5

array([[ 9],
       [10],
       [11]])

In [252]:
# transpose the array

In [253]:
c= np.array([[1,2,3]])

In [254]:
c

array([[1, 2, 3]])

In [255]:
c.T

array([[1],
       [2],
       [3]])

In [256]:
c.T + 4

array([[5],
       [6],
       [7]])

In [257]:
c.T +b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [258]:
p = np.random.rand(3,3)

In [259]:
p

array([[0.68297822, 0.79553288, 0.83982363],
       [0.21984741, 0.13372697, 0.55166946],
       [0.10676963, 0.73363518, 0.98537849]])

In [260]:
np.sqrt(p)

array([[0.82642496, 0.8919265 , 0.91641891],
       [0.46887889, 0.36568698, 0.74274454],
       [0.32675622, 0.85652506, 0.99266232]])

In [261]:
np.exp(p)

array([[1.97976514, 2.21562134, 2.31595846],
       [1.24588661, 1.14308068, 1.73614903],
       [1.1126779 , 2.08263763, 2.67882559]])

In [262]:
np.log10(p)

array([[-0.16559315, -0.09934187, -0.07581191],
       [-0.65787864, -0.87378101, -0.25832106],
       [-0.97155227, -0.13451985, -0.00639692]])

In [263]:
q = np.random.randint(1,5,(5,5))

In [264]:
q

array([[2, 4, 4, 4, 3],
       [3, 3, 1, 1, 1],
       [4, 1, 1, 4, 4],
       [3, 4, 4, 3, 3],
       [2, 4, 2, 2, 2]])

In [265]:
np.log10(q)

array([[0.30103   , 0.60205999, 0.60205999, 0.60205999, 0.47712125],
       [0.47712125, 0.47712125, 0.        , 0.        , 0.        ],
       [0.60205999, 0.        , 0.        , 0.60205999, 0.60205999],
       [0.47712125, 0.60205999, 0.60205999, 0.47712125, 0.47712125],
       [0.30103   , 0.60205999, 0.30103   , 0.30103   , 0.30103   ]])

In [266]:
# when we use random.rand function for generating the array then data will be change at every execution
# but when we use the random.rand alonfg with the seed function then data does not change 

In [267]:
np.random.rand(2,3)

array([[0.42231553, 0.08760714, 0.50041462],
       [0.55274661, 0.94428315, 0.02293584]])

In [268]:
# seed(3) generate the same data everytime

In [269]:
np.random.seed(3)
np.random.rand(3,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ]])

In [270]:
np.random.seed(3)
np.random.rand(2,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309]])